# Generated by Django 5.2.10 on 2026-01-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=100)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'client_register',
            },
        ),
        migrations.CreateModel(
            name='content_detection_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=3000)),
                ('title', models.CharField(max_length=3000)),
                ('channel_title', models.CharField(max_length=3000)),
                ('category', models.CharField(max_length=3000)),
                ('publish_time', models.CharField(max_length=3000)),
                ('content', models.TextField()),
                ('views', models.CharField(max_length=3000)),
                ('likes', models.CharField(max_length=3000)),
                ('dislikes', models.CharField(max_length=3000)),
                ('comment_count', models.CharField(max_length=3000)),
                ('Video_link', models.CharField(max_length=3000)),
                ('publish_date', models.CharField(max_length=3000)),
                ('views_per_day', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'content_detection',
            },
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'detection_accuracy',
            },
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'detection_ratio',
            },
        ),
    ]
