# Generated by Django 5.1.4 on 2026-01-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Remote_User', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='detection_accuracy',
        ),
        migrations.DeleteModel(
            name='detection_ratio',
        ),
    ]
